config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/challenge', to: 'bot_challenge_page/bot_challenge_page#verify_challenge', as: :bot_detect_challenge
  mount Blacklight::Engine => '/'
  root to: 'catalog#index'
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :oai_provider, BlacklightOaiProvider::Routes.new

  mount OkComputer::Engine, at: '/health'

  authenticate :user do
    get '/login', to: 'application#login', as: :login
  end

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :oai_provider
  end
  devise_for :users

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get '/about', to: 'application#about'
  get '/files/final_submissions/:id', to: 'files#solr_download_final_submission', defaults: { remediated: false },
                                      as: :final_submission_file
  get 'files/remediated_final_submissions/:id', to: 'files#solr_download_final_submission',
                                                defaults: { remediated: true }, as: :remediated_final_submission_file

  # Legacy Redirects
  get '/theses/approved/:access_level/:id_prefix-:id/(:all)',
      to: 'legacy_redirect#redirect_original_urls',
      constraints: { id_prefix: /E(:?HT|TD)/, access_level: /WorldWideIndex|PSUonlyIndex|WithheldIndex/ }
  get '/paper/:id/(:all)', to: redirect('/catalog/%{id}'), status: 301
  get '/search', to: redirect('/catalog'), status: 301
  get '/browse', to: redirect('/catalog'), status: 301

  # error pages
  match '500', to: 'errors#render_server_error', via: :all
  match '401', to: 'errors#render_unauthorized', via: :all
  match '404', to: 'errors#render_not_found', via: :all

  # catchall for not predefined requests - keep this at the very bottom of the routes file
  match '*catch_unknown_routes' => 'errors#render_not_found', via: :all
end

app/views/bookmarks/_clear_bookmarks_widget.html.erb
  <%= link_to t('blacklight.bookmarks.clear.action_title'), clear_bookmarks_path, :method => :delete, :data => { :confirm => t('blacklight.bookmarks.clear.action_confirm') }, :class => 'clear-bookmarks btn btn-danger' %>

app/views/bookmarks/_tools.html.erb
<% if render_show_doc_actions_method_from_blacklight? %>
  <%= render(Blacklight::Document::ActionsComponent.new(document: nil, tag: 'div', classes: "#{controller_name}Tools", wrapping_tag: 'span', wrapping_classes: 'btn btn-outline-primary', link_classes: '', actions: document_actions(document_list, options: { document: nil }), options: { document_list: @response.documents }, url_opts: Blacklight::Parameters.sanitize(params.to_unsafe_h))) %>
<% else %>
  <% Deprecation.warn(self, '#render_show_doc_actions is deprecated; use ActionComponents instead') %>
  <ul class="<%= controller_name %>Tools nav nav-pills">
    <%= render_show_doc_actions document_list, document: nil, document_list: @response.documents, url_opts: Blacklight::Parameters.sanitize(params.to_unsafe_h) do |config, inner| %>
      <li class="nav-item">
        <%= inner %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/bookmarks/index.html.erb
<% @page_title = t('blacklight.bookmarks.page_title', :application_name => application_name) %>

<div id="content" class="col-md-12">
  <h1 class='page-heading'><%= t('blacklight.bookmarks.title') %></h1>

  <%- if current_or_guest_user.blank? -%>

    <h2 class='section-heading'><%= t('blacklight.bookmarks.need_login') %></h2>

  <%- elsif @response.documents.blank? -%>

    <h2 class='section-heading'><%= t('blacklight.bookmarks.no_bookmarks') %></h2>
  <% else %>
    <%= render 'sort_and_per_page' %>
    <%= render partial: 'tools', locals: { document_list: @response.documents } %>
    <h2 class='section-heading sr-only visually-hidden'><%= t('blacklight.bookmarks.list_title') %></h2>
    <%= render_document_index @response.documents %>
    <%= render 'results_pagination' %>
  <% end %>
</div>